"""add estado to turno_aceptado

Revision ID: 0516fcde0d31
Revises: 591de280095a
Create Date: 2026-06-26 15:22:03.887070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0516fcde0d31'
down_revision = '591de280095a'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('turno_aceptado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=20), nullable=True))
    op.execute("UPDATE turno_aceptado SET estado = 'abierto' WHERE estado IS NULL")
    with op.batch_alter_table('turno_aceptado', schema=None) as batch_op:
        batch_op.alter_column('estado', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turno_aceptado', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
