"""add avisos_email to usuario and aviso_email table

Revision ID: 091df668a14b
Revises: b633e2c48c9f
Create Date: 2026-06-22 16:41:55.222397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '091df668a14b'
down_revision = 'b633e2c48c9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aviso_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('publicacion_id', sa.Integer(), nullable=True),
    sa.Column('enviado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['publicacion_id'], ['publicacion_cambio.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avisos_email', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('limite_avisos_email', sa.Integer(), server_default='3', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('limite_avisos_email')
        batch_op.drop_column('avisos_email')

    op.drop_table('aviso_email')
    # ### end Alembic commands ###
