"""añade depende_de_id a documento_cambio para hojas encadenadas

Revision ID: 0de75e74af26
Revises: 1f57cef1c0e8
Create Date: 2026-07-24 13:51:43.679907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0de75e74af26'
down_revision = '1f57cef1c0e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento_cambio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('depende_de_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'documento_cambio', ['depende_de_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento_cambio', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('depende_de_id')

    # ### end Alembic commands ###
