"""add motivo_denegacion to documento_cambio

Revision ID: 1181ee9b2dd8
Revises: 8719b0fd144e
Create Date: 2026-07-16 15:18:39.602200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1181ee9b2dd8'
down_revision = '8719b0fd144e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento_cambio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motivo_denegacion', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento_cambio', schema=None) as batch_op:
        batch_op.drop_column('motivo_denegacion')

    # ### end Alembic commands ###
