"""añade mapeo de código de turno y de trabajador de planilla

Revision ID: 16d83172b341
Revises: 7920cee19df7
Create Date: 2026-07-21 12:14:03.550683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16d83172b341'
down_revision = '7920cee19df7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mapeo_codigo_turno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_intercambio_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('franja_horaria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['franja_horaria_id'], ['franja_horaria.id'], ),
    sa.ForeignKeyConstraint(['grupo_intercambio_id'], ['grupo_intercambio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grupo_intercambio_id', 'codigo', name='uq_mapeo_codigo_grupo_codigo')
    )
    op.create_table('mapeo_trabajador_planilla',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unidad_id', sa.Integer(), nullable=False),
    sa.Column('numero_empleado', sa.String(length=20), nullable=False),
    sa.Column('nombre_planilla', sa.String(length=200), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['unidad_id'], ['unidad.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unidad_id', 'numero_empleado', name='uq_mapeo_trabajador_unidad_numero')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mapeo_trabajador_planilla')
    op.drop_table('mapeo_codigo_turno')
    # ### end Alembic commands ###
