"""add categoria_id to unidad and update unique constraint

Revision ID: 1e69918747e1
Revises: 381fe325c589
Create Date: 2026-06-20 21:31:40.885981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e69918747e1'
down_revision = '381fe325c589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unidad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_unidad_nombre_hospital'), type_='unique')
        batch_op.create_unique_constraint('uq_unidad_nombre_hospital_categoria', ['nombre', 'hospital_id', 'categoria_id'])
        batch_op.create_foreign_key(None, 'categoria', ['categoria_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unidad', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_unidad_nombre_hospital_categoria', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_unidad_nombre_hospital'), ['nombre', 'hospital_id'])
        batch_op.drop_column('categoria_id')

    # ### end Alembic commands ###
