"""add factibilidad_motivos to documento_cambio

Revision ID: 1f57cef1c0e8
Revises: fce42d5845ad
Create Date: 2026-07-24 12:50:54.927112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f57cef1c0e8'
down_revision = 'fce42d5845ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento_cambio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('factibilidad_motivos', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento_cambio', schema=None) as batch_op:
        batch_op.drop_column('factibilidad_motivos')

    # ### end Alembic commands ###
