"""añade índices para filtros de matching

Revision ID: 285a7610df2f
Revises: fe34f9af4a2b
Create Date: 2026-07-16 11:06:40.679624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '285a7610df2f'
down_revision = 'fe34f9af4a2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publicacion_cambio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publicacion_cambio_es_sintetica'), ['es_sintetica'], unique=False)
        batch_op.create_index(batch_op.f('ix_publicacion_cambio_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_publicacion_cambio_tipo'), ['tipo'], unique=False)
        batch_op.create_index(batch_op.f('ix_publicacion_cambio_usuario_id'), ['usuario_id'], unique=False)

    with op.batch_alter_table('unidad', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unidad_grupo_intercambio_id'), ['grupo_intercambio_id'], unique=False)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_categoria_id'), ['categoria_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_categoria_id'))

    with op.batch_alter_table('unidad', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unidad_grupo_intercambio_id'))

    with op.batch_alter_table('publicacion_cambio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publicacion_cambio_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_publicacion_cambio_tipo'))
        batch_op.drop_index(batch_op.f('ix_publicacion_cambio_estado'))
        batch_op.drop_index(batch_op.f('ix_publicacion_cambio_es_sintetica'))

    # ### end Alembic commands ###
