"""add mensaje to publicacion_cambio

Revision ID: 381fe325c589
Revises: a015c4a72503
Create Date: 2026-06-20 21:27:22.512850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '381fe325c589'
down_revision = 'a015c4a72503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publicacion_cambio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mensaje', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publicacion_cambio', schema=None) as batch_op:
        batch_op.drop_column('mensaje')

    # ### end Alembic commands ###
