"""add factibilidad_estado, drop factibilidad_verificada

Revision ID: 3a9f874609fe
Revises: 3f8d2428aa64
Create Date: 2026-07-16 13:32:41.273442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a9f874609fe'
down_revision = '3f8d2428aa64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento_cambio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('factibilidad_estado', sa.String(length=20), server_default='no_verificado', nullable=False))
        batch_op.drop_column('factibilidad_verificada')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento_cambio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('factibilidad_verificada', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('factibilidad_estado')

    # ### end Alembic commands ###
