"""add documento_cambio, participante y firma

Revision ID: 3f8d2428aa64
Revises: fe34f9af4a2b
Create Date: 2026-07-16 11:21:20.782513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f8d2428aa64'
down_revision = 'fe34f9af4a2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documento_cambio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('factibilidad_verificada', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match_cambio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('firma_documento_cambio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_firma', sa.DateTime(timezone=True), nullable=False),
    sa.Column('imagen_firma', sa.Text(), nullable=False),
    sa.Column('hash_documento', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documento_cambio.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento_id', 'usuario_id', name='uq_firma_documento_usuario')
    )
    op.create_table('participante_documento_cambio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('turno_cede_fecha', sa.Date(), nullable=False),
    sa.Column('turno_cede_franja_id', sa.Integer(), nullable=False),
    sa.Column('turno_recibe_fecha', sa.Date(), nullable=False),
    sa.Column('turno_recibe_franja_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documento_cambio.id'], ),
    sa.ForeignKeyConstraint(['turno_cede_franja_id'], ['franja_horaria.id'], ),
    sa.ForeignKeyConstraint(['turno_recibe_franja_id'], ['franja_horaria.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento_id', 'usuario_id', name='uq_participante_documento_usuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participante_documento_cambio')
    op.drop_table('firma_documento_cambio')
    op.drop_table('documento_cambio')
    # ### end Alembic commands ###
