"""add fecha_cierre to publicacion_cambio and backfill match fecha_creacion

Revision ID: 40d574d237f8
Revises: 5ca2c2e6d601
Create Date: 2026-06-29 18:13:39.664154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40d574d237f8'
down_revision = '5ca2c2e6d601'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('publicacion_cambio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_cierre', sa.DateTime(), nullable=True))

    # Backfill match_cambio.fecha_creacion NULLs con la fecha de publicación más reciente
    # del match (proxy del momento real: el match no puede ser anterior a la pub más nueva).
    op.execute("""
        UPDATE match_cambio mc
        SET fecha_creacion = COALESCE(
            (SELECT MAX(pc.fecha_creacion)
             FROM match_participacion mp
             JOIN publicacion_cambio pc ON pc.id = mp.publicacion_id
             WHERE mp.match_id = mc.id),
            NOW()
        )
        WHERE mc.fecha_creacion IS NULL
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publicacion_cambio', schema=None) as batch_op:
        batch_op.drop_column('fecha_cierre')

    # ### end Alembic commands ###
