"""add mostrar_disponibilidad to usuario

Revision ID: 4af2ef6f0e6e
Revises: b9d6698355e6
Create Date: 2026-07-22 18:53:32.898706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4af2ef6f0e6e'
down_revision = 'b9d6698355e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mostrar_disponibilidad', sa.Boolean(), server_default='true', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('mostrar_disponibilidad')

    # ### end Alembic commands ###
