"""add origen_papel to documento_cambio

Revision ID: 4b1f1eeadd91
Revises: 4af2ef6f0e6e
Create Date: 2026-07-23 17:24:36.521672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b1f1eeadd91'
down_revision = '4af2ef6f0e6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento_cambio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origen_papel', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento_cambio', schema=None) as batch_op:
        batch_op.drop_column('origen_papel')

    # ### end Alembic commands ###
