"""añade tabla busqueda_guardada

Revision ID: 526774aa6180
Revises: 20b495e68ab6
Create Date: 2026-06-24 23:02:10.316554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526774aa6180'
down_revision = '20b495e68ab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('busqueda_guardada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('filtros', sa.JSON(), nullable=False),
    sa.Column('creada_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('busqueda_guardada')
    # ### end Alembic commands ###
