"""add nota_dia and volcado_planilla

Revision ID: 58a556f9da30
Revises: fa7e294c3216
Create Date: 2026-06-28 14:41:05.676060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58a556f9da30'
down_revision = 'fa7e294c3216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nota_dia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'fecha', name='uq_nota_dia_usuario_fecha')
    )
    with op.batch_alter_table('match_participacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('volcado_planilla', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_participacion', schema=None) as batch_op:
        batch_op.drop_column('volcado_planilla')

    op.drop_table('nota_dia')
    # ### end Alembic commands ###
