"""añade onboarding_visto a usuario

Revision ID: 591de280095a
Revises: 57cd51ef0fab
Create Date: 2026-06-26 08:18:19.613635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '591de280095a'
down_revision = '57cd51ef0fab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboarding_visto', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('onboarding_visto')

    # ### end Alembic commands ###
