"""add fecha_creacion and fecha_confirmacion_total to match_cambio

Revision ID: 653ed2f64432
Revises: 0516fcde0d31
Create Date: 2026-06-26 19:51:39.038662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '653ed2f64432'
down_revision = '0516fcde0d31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_cambio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fecha_confirmacion_total', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_cambio', schema=None) as batch_op:
        batch_op.drop_column('fecha_confirmacion_total')
        batch_op.drop_column('fecha_creacion')

    # ### end Alembic commands ###
