"""añade tabla unidad_supervisada

Revision ID: 666dde3fff3c
Revises: 0de75e74af26
Create Date: 2026-07-25 22:45:07.008735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '666dde3fff3c'
down_revision = '0de75e74af26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unidad_supervisada',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('unidad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['unidad_id'], ['unidad.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'unidad_id')
    )
    # ### end Alembic commands ###
    op.execute(
        "INSERT INTO unidad_supervisada (usuario_id, unidad_id) "
        "SELECT id, unidad_id FROM usuario WHERE es_supervisora = true"
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unidad_supervisada')
    # ### end Alembic commands ###
