"""añade firma digital a la confirmación de matches

Revision ID: 76121be7a1b5
Revises: 285a7610df2f
Create Date: 2026-07-16 18:25:19.201028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76121be7a1b5'
down_revision = '285a7610df2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_participacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firma_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_participacion', schema=None) as batch_op:
        batch_op.drop_column('firma_data')

    # ### end Alembic commands ###
