"""add pais, provincia, ciudad; hospital ciudad_id FK

Revision ID: 7639521795fd
Revises: 1e69918747e1
Create Date: 2026-06-21 08:34:59.571578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7639521795fd'
down_revision = '1e69918747e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('provincia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pais_id'], ['pais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', 'pais_id', name='uq_provincia_nombre_pais')
    )
    op.create_table('ciudad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('provincia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['provincia_id'], ['provincia.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', 'provincia_id', name='uq_ciudad_nombre_provincia')
    )
    with op.batch_alter_table('hospital', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ciudad_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('hospital_nombre_key'), type_='unique')
        batch_op.create_unique_constraint('uq_hospital_nombre_ciudad', ['nombre', 'ciudad_id'])
        batch_op.create_foreign_key(None, 'ciudad', ['ciudad_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospital', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_hospital_nombre_ciudad', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('hospital_nombre_key'), ['nombre'])
        batch_op.drop_column('ciudad_id')

    op.drop_table('ciudad')
    op.drop_table('provincia')
    op.drop_table('pais')
    # ### end Alembic commands ###
