"""add publicacion_id to notificacion

Revision ID: 77b62b430dcf
Revises: fae054ab0439
Create Date: 2026-06-23 19:52:57.339991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77b62b430dcf'
down_revision = 'fae054ab0439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publicacion_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'publicacion_cambio', ['publicacion_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificacion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('publicacion_id')

    # ### end Alembic commands ###
