"""add firma_supervisora a documento_cambio

Revision ID: 7920cee19df7
Revises: 93549d8020ab
Create Date: 2026-07-17 19:54:42.971292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7920cee19df7'
down_revision = '93549d8020ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento_cambio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firma_supervisora', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento_cambio', schema=None) as batch_op:
        batch_op.drop_column('firma_supervisora')

    # ### end Alembic commands ###
