"""añade tablas feature_flag y feature_flag_unidad

Revision ID: 7be3ca3f48b9
Revises: 666dde3fff3c
Create Date: 2026-07-26 11:11:45.274951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7be3ca3f48b9'
down_revision = '666dde3fff3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_flag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('activo_global', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('feature_flag_unidad',
    sa.Column('feature_flag_id', sa.Integer(), nullable=False),
    sa.Column('unidad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feature_flag_id'], ['feature_flag.id'], ),
    sa.ForeignKeyConstraint(['unidad_id'], ['unidad.id'], ),
    sa.PrimaryKeyConstraint('feature_flag_id', 'unidad_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feature_flag_unidad')
    op.drop_table('feature_flag')
    # ### end Alembic commands ###
