"""add limite_dias_consecutivos a grupo_intercambio

Revision ID: 7ed9c5cc5e02
Revises: 4b1f1eeadd91
Create Date: 2026-07-23 18:18:16.249188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ed9c5cc5e02'
down_revision = '4b1f1eeadd91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grupo_intercambio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('limite_dias_consecutivos', sa.Integer(), server_default='8', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grupo_intercambio', schema=None) as batch_op:
        batch_op.drop_column('limite_dias_consecutivos')

    # ### end Alembic commands ###
