"""add estado_dia_planilla

Revision ID: 83435455d710
Revises: a05e3c7ee0d9
Create Date: 2026-06-28 13:05:48.801749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83435455d710'
down_revision = 'a05e3c7ee0d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estado_dia_planilla',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'fecha', name='uq_estado_dia_usuario_fecha')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estado_dia_planilla')
    # ### end Alembic commands ###
