"""add feedback table

Revision ID: 866f864194ce
Revises: eb73fa595a09
Create Date: 2026-06-22 18:35:07.529293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '866f864194ce'
down_revision = 'eb73fa595a09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('email_contacto', sa.String(length=200), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    # ### end Alembic commands ###
