"""add decision_supervisora fields to documento_cambio

Revision ID: 8719b0fd144e
Revises: 928e2599c80a
Create Date: 2026-07-16 15:07:13.227845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8719b0fd144e'
down_revision = '928e2599c80a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento_cambio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decision_supervisora', sa.String(length=20), server_default='pendiente', nullable=False))
        batch_op.add_column(sa.Column('supervisora_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fecha_decision_supervisora', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_foreign_key(None, 'usuario', ['supervisora_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento_cambio', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fecha_decision_supervisora')
        batch_op.drop_column('supervisora_id')
        batch_op.drop_column('decision_supervisora')

    # ### end Alembic commands ###
