"""add firma_guardada a usuario

Revision ID: 8ea99af48f5f
Revises: b6770d428a60
Create Date: 2026-07-17 14:00:09.701363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ea99af48f5f'
down_revision = 'b6770d428a60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firma_guardada', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('firma_guardada')

    # ### end Alembic commands ###
