"""add es_supervisora to usuario

Revision ID: 928e2599c80a
Revises: c2938aae9b98
Create Date: 2026-07-16 14:48:38.601634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928e2599c80a'
down_revision = 'c2938aae9b98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_supervisora', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('es_supervisora')

    # ### end Alembic commands ###
