"""add mensaje to notificacion

Revision ID: 9310c6bbcb55
Revises: 40d574d237f8
Create Date: 2026-07-08 18:07:01.340531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9310c6bbcb55'
down_revision = '40d574d237f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mensaje', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificacion', schema=None) as batch_op:
        batch_op.drop_column('mensaje')

    # ### end Alembic commands ###
