"""add anulacion fields to documento_cambio

Revision ID: 93549d8020ab
Revises: b6770d428a60
Create Date: 2026-07-17 17:16:49.304638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93549d8020ab'
down_revision = '8ea99af48f5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento_cambio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anulado', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('anulado_por_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fecha_anulacion', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('motivo_anulacion', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'usuario', ['anulado_por_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento_cambio', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('motivo_anulacion')
        batch_op.drop_column('fecha_anulacion')
        batch_op.drop_column('anulado_por_id')
        batch_op.drop_column('anulado')

    # ### end Alembic commands ###
