"""add planilla turnos y planilla mes

Revision ID: a05e3c7ee0d9
Revises: debdf1123e04
Create Date: 2026-06-28 11:40:41.306197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a05e3c7ee0d9'
down_revision = 'debdf1123e04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planilla_mes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('anyo', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('publicada', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'anyo', 'mes', name='uq_planilla_mes_usuario')
    )
    op.create_table('turno_planilla',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('franja_horaria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['franja_horaria_id'], ['franja_horaria.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'fecha', 'franja_horaria_id', name='uq_turno_planilla_usuario_fecha_franja')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turno_planilla')
    op.drop_table('planilla_mes')
    # ### end Alembic commands ###
