"""add notif_email_documento_cambio a usuario

Revision ID: a18f63631b51
Revises: 1181ee9b2dd8
Create Date: 2026-07-16 15:30:57.594049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a18f63631b51'
down_revision = '1181ee9b2dd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notif_email_documento_cambio', sa.Boolean(), server_default='true', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('notif_email_documento_cambio')

    # ### end Alembic commands ###
