"""schema inicial completo

Revision ID: a591a4bb98fb
Revises: 
Create Date: 2026-06-20 11:39:54.975601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a591a4bb98fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('grupo_intercambio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hospital',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('match_cambio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('franja_horaria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('grupo_intercambio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_intercambio_id'], ['grupo_intercambio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', 'grupo_intercambio_id', name='uq_franja_nombre_grupo')
    )
    op.create_table('unidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('grupo_intercambio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_intercambio_id'], ['grupo_intercambio.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', 'hospital_id', name='uq_unidad_nombre_hospital')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('unidad_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('push_subscription', sa.Text(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['unidad_id'], ['unidad.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('notificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match_cambio.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publicacion_cambio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turno_aceptado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publicacion_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('franja_horaria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['franja_horaria_id'], ['franja_horaria.id'], ),
    sa.ForeignKeyConstraint(['publicacion_id'], ['publicacion_cambio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turno_cedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publicacion_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('franja_horaria_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['franja_horaria_id'], ['franja_horaria.id'], ),
    sa.ForeignKeyConstraint(['publicacion_id'], ['publicacion_cambio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_participacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('publicacion_id', sa.Integer(), nullable=False),
    sa.Column('turno_cedido_id', sa.Integer(), nullable=False),
    sa.Column('confirmado', sa.Boolean(), nullable=False),
    sa.Column('fecha_confirmacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['match_cambio.id'], ),
    sa.ForeignKeyConstraint(['publicacion_id'], ['publicacion_cambio.id'], ),
    sa.ForeignKeyConstraint(['turno_cedido_id'], ['turno_cedido.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'publicacion_id', name='uq_match_publicacion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_participacion')
    op.drop_table('turno_cedido')
    op.drop_table('turno_aceptado')
    op.drop_table('publicacion_cambio')
    op.drop_table('notificacion')
    op.drop_table('usuario')
    op.drop_table('unidad')
    op.drop_table('franja_horaria')
    op.drop_table('match_cambio')
    op.drop_table('hospital')
    op.drop_table('grupo_intercambio')
    op.drop_table('categoria')
    # ### end Alembic commands ###
