"""add tipo a documento_cambio y amplia constraint participante

Revision ID: aec48c5be24e
Revises: 576142da40ac
Create Date: 2026-07-27 18:09:54.160874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aec48c5be24e'
down_revision = '576142da40ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento_cambio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=20), server_default='cambio', nullable=False))

    with op.batch_alter_table('participante_documento_cambio', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_participante_documento_usuario'), type_='unique')
        batch_op.create_unique_constraint('uq_participante_documento_usuario', ['documento_id', 'usuario_id', 'turno_cede_fecha', 'turno_cede_franja_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participante_documento_cambio', schema=None) as batch_op:
        batch_op.drop_constraint('uq_participante_documento_usuario', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_participante_documento_usuario'), ['documento_id', 'usuario_id'])

    with op.batch_alter_table('documento_cambio', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
