"""add cualquier_franja to turno_aceptado, nullable franja_horaria_id

Revision ID: b633e2c48c9f
Revises: f7fbad145c0f
Create Date: 2026-06-22 16:36:58.239593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b633e2c48c9f'
down_revision = 'f7fbad145c0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turno_aceptado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cualquier_franja', sa.Boolean(), nullable=True))
        batch_op.alter_column('franja_horaria_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.execute("UPDATE turno_aceptado SET cualquier_franja = FALSE WHERE cualquier_franja IS NULL")

    with op.batch_alter_table('turno_aceptado', schema=None) as batch_op:
        batch_op.alter_column('cualquier_franja', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turno_aceptado', schema=None) as batch_op:
        batch_op.alter_column('franja_horaria_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('cualquier_franja')

    # ### end Alembic commands ###
