"""add ajuste_planilla_supervisora

Revision ID: b9d6698355e6
Revises: 16d83172b341
Create Date: 2026-07-21 13:29:05.413848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9d6698355e6'
down_revision = '16d83172b341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ajuste_planilla_supervisora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('realizado_por_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('descripcion_anterior', sa.String(length=200), nullable=False),
    sa.Column('descripcion_nueva', sa.String(length=200), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['realizado_por_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ajuste_planilla_supervisora')
    # ### end Alembic commands ###
