"""elimina aviso_email y columnas email en usuario

Revision ID: c095ab8987d3
Revises: 77b62b430dcf
Create Date: 2026-06-23 21:49:59.014222

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c095ab8987d3'
down_revision = '77b62b430dcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aviso_email')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('limite_avisos_email')
        batch_op.drop_column('avisos_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avisos_email', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('limite_avisos_email', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=False))

    op.create_table('aviso_email',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('publicacion_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('enviado_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['publicacion_id'], ['publicacion_cambio.id'], name=op.f('aviso_email_publicacion_id_fkey')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('aviso_email_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('aviso_email_pkey'))
    )
    # ### end Alembic commands ###
