"""add documento_cambio_id to notificacion

Revision ID: c2938aae9b98
Revises: 3a9f874609fe
Create Date: 2026-07-16 13:59:50.432510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2938aae9b98'
down_revision = '3a9f874609fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documento_cambio_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'documento_cambio', ['documento_cambio_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificacion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('documento_cambio_id')

    # ### end Alembic commands ###
