"""añade notif_publicacion a usuario

Revision ID: d729300ac4c8
Revises: c095ab8987d3
Create Date: 2026-06-23 22:06:34.473265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd729300ac4c8'
down_revision = 'c095ab8987d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notif_publicacion', sa.Boolean(), server_default='true', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('notif_publicacion')

    # ### end Alembic commands ###
