"""añade audit_eliminacion para contar cambios eliminados

Revision ID: debdf1123e04
Revises: e8e3d3c815bd
Create Date: 2026-06-28 10:34:01.871436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'debdf1123e04'
down_revision = 'e8e3d3c815bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_eliminacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unidad_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['unidad_id'], ['unidad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_eliminacion')
    # ### end Alembic commands ###
