"""añade tabla usuario_unidad

Revision ID: def6b117664c
Revises: 4d4eb855caee
Create Date: 2026-07-31 11:57:27.626848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'def6b117664c'
down_revision = '4d4eb855caee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario_unidad',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('unidad_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['unidad_id'], ['unidad.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'unidad_id')
    )
    # ### end Alembic commands ###
    op.execute(
        "INSERT INTO usuario_unidad (usuario_id, unidad_id, categoria_id) "
        "SELECT id, unidad_id, categoria_id FROM usuario"
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_unidad')
    # ### end Alembic commands ###
