"""add color to franja_horaria

Revision ID: e2f9e8059eaa
Revises: 58a556f9da30
Create Date: 2026-06-28 15:26:47.201304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2f9e8059eaa'
down_revision = '58a556f9da30'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('franja_horaria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=7), nullable=True))

    # Backfill colores para franjas existentes según nombre
    op.execute("UPDATE franja_horaria SET color = '#1E3A8A' WHERE LOWER(nombre) LIKE '%noche%'    AND color IS NULL")
    op.execute("UPDATE franja_horaria SET color = '#1E40AF' WHERE LOWER(nombre) LIKE '%nocturno%' AND color IS NULL")
    op.execute("UPDATE franja_horaria SET color = '#3B82F6' WHERE LOWER(nombre) LIKE '%mañana%'   AND color IS NULL")
    op.execute("UPDATE franja_horaria SET color = '#F97316' WHERE LOWER(nombre) LIKE '%tarde%'    AND color IS NULL")
    op.execute("UPDATE franja_horaria SET color = '#14B8A6' WHERE LOWER(nombre) LIKE '%diurno%'   AND color IS NULL")
    # Resto de franjas sin nombre reconocido: asignar colores en orden por grupo
    op.execute("""
        UPDATE franja_horaria f
        SET color = (
            ARRAY['#8B5CF6','#EC4899','#22C55E','#EAB308','#6366F1','#F43F5E','#06B6D4']
        )[((
            SELECT COUNT(*) FROM franja_horaria f2
            WHERE f2.grupo_intercambio_id = f.grupo_intercambio_id
              AND f2.id < f.id
              AND f2.color IS NOT NULL
        ) % 7) + 1]
        WHERE f.color IS NULL
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('franja_horaria', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
