"""añade notif_busqueda_guardada en usuario y busqueda_guardada_id en notificacion

Revision ID: e93a778414b8
Revises: 526774aa6180
Create Date: 2026-06-24 23:55:11.199124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e93a778414b8'
down_revision = '526774aa6180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('busqueda_guardada_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'busqueda_guardada', ['busqueda_guardada_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notif_busqueda_guardada', sa.Boolean(), server_default='true', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('notif_busqueda_guardada')

    with op.batch_alter_table('notificacion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('busqueda_guardada_id')

    # ### end Alembic commands ###
