"""add tipo to publicacion_cambio, nullable turno_cedido_id and turno_aceptado_id in match_participacion

Revision ID: f7fbad145c0f
Revises: 7639521795fd
Create Date: 2026-06-22 16:30:34.720503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7fbad145c0f'
down_revision = '7639521795fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_participacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('turno_aceptado_id', sa.Integer(), nullable=True))
        batch_op.alter_column('turno_cedido_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'turno_aceptado', ['turno_aceptado_id'], ['id'])

    with op.batch_alter_table('publicacion_cambio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=20), nullable=True))

    op.execute("UPDATE publicacion_cambio SET tipo = 'cambio' WHERE tipo IS NULL")

    with op.batch_alter_table('publicacion_cambio', schema=None) as batch_op:
        batch_op.alter_column('tipo', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publicacion_cambio', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    with op.batch_alter_table('match_participacion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('turno_cedido_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('turno_aceptado_id')

    # ### end Alembic commands ###
