"""add push prefs and suscripcion_publicaciones

Revision ID: f9b9fbe4eb59
Revises: 866f864194ce
Create Date: 2026-06-23 00:05:23.350198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9b9fbe4eb59'
down_revision = '866f864194ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suscripcion_publicaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suscriptor_id', sa.Integer(), nullable=False),
    sa.Column('publicador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['publicador_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['suscriptor_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('suscriptor_id', 'publicador_id', name='uq_suscripcion')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('push_activo', sa.Boolean(), server_default='true', nullable=False))
        batch_op.add_column(sa.Column('notif_match', sa.Boolean(), server_default='true', nullable=False))
        batch_op.add_column(sa.Column('notif_confirmacion_parcial', sa.Boolean(), server_default='true', nullable=False))
        batch_op.add_column(sa.Column('notif_confirmado_total', sa.Boolean(), server_default='true', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('notif_confirmado_total')
        batch_op.drop_column('notif_confirmacion_parcial')
        batch_op.drop_column('notif_match')
        batch_op.drop_column('push_activo')

    op.drop_table('suscripcion_publicaciones')
    # ### end Alembic commands ###
