"""add compatibilidad_planilla

Revision ID: fa7e294c3216
Revises: 83435455d710
Create Date: 2026-06-28 13:45:11.801549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa7e294c3216'
down_revision = '83435455d710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compatibilidad_planilla',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publicacion_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['publicacion_id'], ['publicacion_cambio.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('publicacion_id', 'usuario_id', name='uq_compat_planilla_pub_usuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compatibilidad_planilla')
    # ### end Alembic commands ###
