"""add leido to feedback

Revision ID: fae054ab0439
Revises: f9b9fbe4eb59
Create Date: 2026-06-23 12:29:28.204631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fae054ab0439'
down_revision = 'f9b9fbe4eb59'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leido', sa.Boolean(), nullable=True))
    op.execute("UPDATE feedback SET leido = FALSE WHERE leido IS NULL")
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.alter_column('leido', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_column('leido')

    # ### end Alembic commands ###
