"""add mostrar_oportunidad_3 and mostrar_oportunidad_4 to usuario

Revision ID: fe34f9af4a2b
Revises: f182c4111872
Create Date: 2026-07-10 22:11:46.149448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe34f9af4a2b'
down_revision = 'f182c4111872'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mostrar_oportunidad_3', sa.Boolean(), server_default='true', nullable=False))
        batch_op.add_column(sa.Column('mostrar_oportunidad_4', sa.Boolean(), server_default='true', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('mostrar_oportunidad_4')
        batch_op.drop_column('mostrar_oportunidad_3')

    # ### end Alembic commands ###
